/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.basicfamily.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DslScopeProvider extends AbstractDslScopeProvider {

}
