/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.basicfamily.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslUiModule extends AbstractDslUiModule {

	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
