/*
 * generated by Xtext 2.25.0
 */
package org.rm2pt.sample.basicfamily.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
